name: sciptv

on:
  schedule:
    - cron: '0 21 1 * *'
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run SCIPTV
        run: python ${{ github.workspace }}/SCIPTV.py

      #- name: Run cctv
        #run: python ${{ github.workspace }}/cctv.py
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
        
      #- name: Run qita
        #run: python ${{ github.workspace }}/qita.py
        
      - name: Save changes to a file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ -f "lives.txt" ]]; then
          git add lives.txt
          fi
          if ! git diff --staged --quiet; then
          git commit -m "Auto-update live"
          git push
          fi
