name: sciptv

on:
  schedule:
    - cron: '0 21 1 * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run SCIPTV
        run: python ${{ github.workspace }}/SCIPTV.py

      #- name: Run cctv
        #run: python ${{ github.workspace }}/cctv.py
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
        
      #- name: Run qita
        #run: python ${{ github.workspace }}/qita.py
        
      - name: Save changes to a file
        run: |
          git config --local user.email "95021138@qq.com"
          git config --local user.name "cymz6"
          echo "Changes made on $(date)" > ${{ github.workspace }}/$(date +%Y-%m-%d).txt
          git add $(date +%Y-%m-%d).txt
          git commit -m "Add changes made on $(date)"
          git push
